#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           SIGAJA DEPLOYMENT - FOLLOW THESE STEPS              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: DEPLOY BACKEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  cd backend"
echo "  vercel"
echo ""
echo "📝 WRITE DOWN THE URL IT GIVES YOU!"
echo "   Example: https://sigaja-backend-abc123.vercel.app"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: UPDATE FRONTEND .ENV FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Edit the file: frontend/.env.production"
echo ""
echo "Replace the content with:"
echo ""
echo "  VITE_API_URL=https://YOUR-ACTUAL-BACKEND-URL.vercel.app/"
echo ""
echo "⚠️  IMPORTANT: Replace YOUR-ACTUAL-BACKEND-URL with the URL from Step 1!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: DEPLOY FRONTEND"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run these commands:"
echo ""
echo "  cd frontend"
echo "  npm run build"
echo "  vercel --prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ABOUT THE ERRORS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "EventEmitter warnings (contentscript.js):"
echo "  → These are from MetaMask/browser extension"
echo "  → NOT from your code"
echo "  → CANNOT be fixed by you"
echo "  → Are HARMLESS"
echo "  → IGNORE THEM!"
echo ""
echo "CORS error (your-backend-url.vercel.app):"
echo "  → You're using a PLACEHOLDER URL"
echo "  → You need to DEPLOY YOUR BACKEND first"
echo "  → Then update the frontend with the REAL URL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
